### ISSUE TITLE
报错咯~

### ISSUE THREAD

**Issue by shellsec** [moozik/avmoo-spider#10]
url:https://avmoo.sbs/cn/genre/dd21aefe7ae3228c,page_limit:100
Exception in thread Thread-1 (spider_thread):
Traceback (most recent call last):
  File "C:\python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\项目开发\avmoo-spider\avmoo-spider-master\flask_avmo.py", line 707, in spider_thread
    common.get_exist_linkid(page_type, keyword))
  File "D:\项目开发\avmoo-spider\avmoo-spider-master\common.py", line 258, in get_exist_linkid
    sql = "SELECT linkid FROM av_list WHERE genre LIKE '%|{}|%'".format(genre[0]['name'])
IndexError: list index out of range

**Comment by moozik** [comment]
修复了

**Comment by shellsec** [comment]
import spider_avmo
  File "D:\项目开发\avmoo-spider\avmoo-spider-master\spider_avmo.py", line 11, in <module>
    class Avmo:
  File "D:\项目开发\avmoo-spider\avmoo-spider-master\spider_avmo.py", line 135, in Avmo
    def crawl_by_movie_linkid(self, movie_linkid: str) -> List[int, dict]:
  File "C:\python310\lib\typing.py", line 309, in inner
    return func(*args, **kwds)
  File "C:\python310\lib\typing.py", line 1120, in __getitem__
    _check_generic(self, params, self._nparams)
  File "C:\python310\lib\typing.py", line 228, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
TypeError: Too many arguments for typing.List; actual 2, expected 1

**Comment by moozik** [comment]
又修复了，体验了一下新用户的感受
